### ISSUE TITLE
How to disable code reloading in production env

### ISSUE THREAD

**Issue by teohm** [hanami/reloader#10]
Given that `hanami-reloader` overrides the `hanami server` CLI, what is the expected way to disable it in production?

**Comment by katafrakt** [comment]
That's a good question, +1 for that. Perhaps server command should only be overridden in dev env?

**Comment by teohm** [comment]
Yes, that makes sense. Should we proceed with this idea? I'm happy to help if necessary

**Comment by katafrakt** [comment]
@jodosha any thoughts?

**Comment by fny** [comment]
You can always put  `gem 'hanami-reloader', require: ENV['RACK_ENV'] != 'production'` in your Gemfile

**Comment by katafrakt** [comment]
I created a PR for that some time ago: https://github.com/hanami/reloader/pull/11

**Comment by jodosha** [comment]
@teohm Thanks for reporting this. Two things:

1. You should add `hanami-reloader` into the `:development` group in your `Gemfile` and run `bundle install --without development test`, which won't install gems from these `Gemfile` groups. No gem, no overriding.
1. Instead of using `hanami server` in production, I highly recommend to use directly `puma` CLI (or the equivalent provided by your Ruby web server of choice.
